### ISSUE TITLE
Gulp Minify CSS depreciated

### ISSUE THREAD

**Issue by mattada** [factor1/factor1_blankwp#18]
Due to the depreciation of the minifyCSS package, we need to update factor1_blank to rely on cssnano. 
https://www.npmjs.com/package/cssnano

**Comment by buschschwick** [comment]
https://www.npmjs.com/package/gulp-cssnano is the correct package we will be implementing.

**Comment by buschschwick** [comment]
This has been added, tested, and implemented in https://github.com/factor1/factor1_blankwp/commit/458a4957ab815df136039555071995491b7424fd
