### ISSUE TITLE
Rebrand Theme

### ISSUE THREAD

**Issue by mattada** [factor1/factor1_blankwp#19]
To help us remain fluid, and sharing this as a resource for others to use, we need to re-brand this. 

Current name is rooted in our company brand, and Blank Wp, a theme created for the DigWP book in 2010. https://digwp.com/2010/02/blank-wordpress-theme/

**Comment by buschschwick** [comment]
Have we had any ideas on where to go from here? @mattada @bebaps

**Comment by mattada** [comment]
Not directly. I want to focus on something relating to this being the core, baseline, or foundational. Words like this come to mind when I brainstorm this. 

Scaffolding, Anchor, Bedrock, Concrete, Framing, frame, stacks. 

Im sure i have more, just cant remember them at the moment.

**Comment by mattada** [comment]
I lean construction because it's more logical for me. But with the right theme. it could be anything.

**Comment by mattada** [comment]
blast off, alpha, square one, clean slate, prelude, takeoff,

**Comment by mattada** [comment]
New name final contented: Prelude.
