### ISSUE TITLE
Add required WP CSS Classes

### ISSUE THREAD

**Issue by buschschwick** [factor1/factor1_blankwp#6]
REQUIRED:.alignright css class is needed in your theme css.
REQUIRED:.alignleft css class is needed in your theme css.
REQUIRED:.aligncenter css class is needed in your theme css.

These classes are used by the WP Content Editor when aligning items. Make sure we have it in our CSS.

**Comment by mattada** [comment]
Im shocked this isnt already part of our core utility classes.

**Comment by mattada** [comment]
These can replace the older css classes (.img-left, .align-left) on lines 133 and 134 of _global.scss

**Comment by buschschwick** [comment]
This was added in update 2.0.5
